services: 
  # Apache y PHP
  web:
    build: .
    links: 
      - "db:db"
    ports:
      - "8080:80"
    environment: 
      APACHE_RUN_USER: "#1000"
      APACHE_RUN_GROUP: "#1000"
    expose:
      - 9003
    volumes:
      - ./www:/var/www/html/
      - ./dwes.es:/var/www/dwes.es
      - ./examen.com:/var/web/examen.com
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        #      - ./php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
    - "host.docker.internal:host-gateway"
  
  # Base de datos 
  db:
    image: "postgres"
    shm_size: "128m"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

